import './globals.css'
import { Inter } from 'next/font/google'
import Header  from './common/header'
import Footer from './common/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Header/>
        <body>{children}</body>
      <Footer/>
    </div>
      
  )
}